angular.module("automap")
.constant("$tips", [
	'TO CREATE A GOBAN, JAST VISIT https://goban.tw/YOUR_FOLDER',
	'CLICK "CREATE" TO ENTER EDITOR',
	'IN ETHERCALC EDITOR, TYPE YOUR_TITLE INTO B2 CELL',
	'PASTE AN URL YOU LIKE INTO A3 CELL',
	'TYPE A NAME OF THIS URL INTO B3 CELL',
	'RELOAD TO ENJOY YOUR FIRST GOBAN',
	])