angular.module('weApp')
	.factory("$backup", myBackup);


function myBackup () {
	return {
  "hands" : [ {
    "Style" : "large_green",
    "address" : "新竹市",
    "ask" : "中文教學專業成長",
    "check" : "請勾這格, 要勾, 勾本格",
    "connect_me" : "zona12370388@gmail.com",
    "hometown" : "Tainan, Taiwan",
    "id" : "100002945639081",
    "latlngColumn" : "24.80619,120.96892",
    "learner_birth" : "1986",
    "learner_habit" : "閱讀, 占星, 廚藝",
    "learner_role" : "獨立教育工作者",
    "learner_type" : "三五好友",
    "name" : "賴佳祺",
    "note" : "大學時期積極參與社團，從學生活動延申到學生運動\n\n關心環境保護與人權，期許自己成為知行合一的教育實踐者",
    "online" : false,
    "rowid" : "",
    "share" : "easy烘培",
    "site" : "http://www.happygifts.org.tw/index.do",
    "site2" : "",
    "username" : "ZonaLai",
    "時間戳記" : "2013/2/2 下午 4:32:09"
  }, {
    "Style" : "large_green",
    "address" : "新北市板橋區明德街",
    "ask" : "有機體教育",
    "check" : "請勾這格, 要勾, 勾本格",
    "child_birth" : "2006",
    "child_birth2" : "2008",
    "connect_me" : "E-MAIL: jetinchao@gmail.com\n手機: 0987-071072",
    "freetime" : "週一～週六 09:00~17:00",
    "hometown" : "Taipei, Taiwan",
    "id" : "1657645997",
    "invis" : false,
    "latlngColumn" : "25.01021,121.459793",
    "learner_birth" : "1978",
    "learner_habit" : "音樂、創業",
    "learner_role" : "自學家長 + 獨立教育工作者",
    "learner_type" : "團體共學",
    "name" : "趙介亭",
    "note" : "展賦教育文創，探索自我、開展天賦",
    "online" : false,
    "rowid" : "",
    "share" : "有機體教育與教養",
    "site" : "http://opengift.com.tw",
    "site2" : "https://www.facebook.com/opengiftedu",
    "username" : "jetinchao",
    "時間戳記" : "2013/2/3 下午 8:16:34"
  }, {
    "Style" : "large_green",
    "address" : "花蓮縣吉安鄉",
    "ask" : "認識花蓮地區對自學有興趣的各學科的教學者",
    "check" : "請勾這格, 要勾, 勾本格",
    "connect_me" : "Email：annhua99@gmail.com<br>手機：0911118331",
    "hometown" : "undefined",
    "id" : "1746920311",
    "latlngColumn" : "23.97345,121.56319",
    "learner_birth" : "1965",
    "learner_habit" : "生命故事敘說、薩提爾家族治療",
    "learner_role" : "獨立教育工作者",
    "learner_type" : "類學校機構",
    "name" : "張天安",
    "note" : "體制內數學教師兼導師五年半，體制外（青少年全人教育實驗學校）數學教師、輔導教師共十一年，在台中市成立「台灣青少年教育協進會」推展在家自學的共學團體約兩年。\n目前在花蓮縣以諮商心理師的身分做個人工作，參與花蓮的在地社團「台灣多元跨界行動協會」，有餘力時關注教育事務，醞釀形成自學的環境。\n目前協助丁志仁以團體或機構實驗教育的名義，掛籍在新北市新埔國中，實踐國高中合併的「六年制學程」的實驗計畫（http://jendo.org/jendo/）。",
    "rowid" : "",
    "share" : "自我探索課程、心理輔導",
    "site" : "facebook.com/annhua99",
    "site2" : "http://jendo.org/jendo/",
    "username" : "annhua99",
    "時間戳記" : "2013/4/29 下午 6:21:19"
  }, {
    "Style" : "large_yellow",
    "address" : "台北市士林區天母東路",
    "ask" : "共學資源",
    "check" : "請勾這格",
    "child_birth" : "2004",
    "child_birth2" : "2008",
    "connect_me" : "lunwei@gmail.com",
    "freetime" : "週一至週五",
    "hometown" : "undefined",
    "id" : "100000041840134",
    "latlngColumn" : "25.117565,121.5326",
    "learner_birth" : "1975",
    "learner_habit" : "電影、電腦資訊、戶外活動、旅遊",
    "learner_role" : "自學家長",
    "learner_type" : "個人",
    "name" : "張倫維",
    "note" : "我們家是第一年進行自學的家長，歡迎在這個主題上的一切交流與分享！\n\n我們家有三個小朋友，最小的將在今年跨入小學的門檻。大的兩個在今年都已經開始自學，也會希望他們可以持續在這個不一樣的環境下快樂的學習。",
    "online" : false,
    "rowid" : "-1",
    "share" : "電腦資訊",
    "site" : "http://2fno74.blogspot.tw",
    "site2" : "",
    "username" : "kenneth.chang.319",
    "時間戳記" : "2013/5/28 下午 10:06:32"
  }, {
    "Style" : "large_blue",
    "address" : "台南市北區南園街127巷22弄",
    "ask" : "目前無",
    "check" : "請勾這格, 要勾, 勾本格",
    "connect_me" : "yulin729@gmail.com",
    "hometown" : "undefined",
    "id" : "1572837285",
    "invis" : false,
    "latlngColumn" : "23.006874,120.226646",
    "learner_birth" : "1976",
    "learner_habit" : "糧食議題,環境教育,NGO組織發展",
    "learner_role" : "獨立教育工作者",
    "learner_type" : "團體共學",
    "name" : "陳郁玲",
    "note" : "",
    "rowid" : "-1",
    "share" : "糧食議題,環境教育,NGO組織發展",
    "site" : "https://www.facebook.com/yulin729",
    "site2" : "",
    "username" : "yulin729",
    "時間戳記" : "2013/8/19 下午 8:29:54"
  }, {
    "Style" : "large_green",
    "address" : "台北市大同區南京西路",
    "ask" : "自學最缺的就是同學, 一起當同學吧",
    "check" : "請勾這格, 要勾, 勾本格",
    "connect_me" : "vincentgotu@gmail.com",
    "freetime" : "都有哦!",
    "hometown" : "Taipei, Taiwan",
    "id" : "1245523074",
    "latlngColumn" : "25.053434,121.514656",
    "learner_birth" : "1975",
    "learner_habit" : "討論自學如何改變台灣學制",
    "learner_role" : "獨立教育工作者",
    "learner_type" : "三五好友",
    "name" : "程彥勳",
    "note" : "身為一個一歲小朋友的爸爸, 現在想她的未來教育還太早, 但是總是會擔心. 為什麼呢? 因為之前擔任過學校代課老師, 補習班老師, 家教老師, 感覺國內的教育環境真是糟, 從上到下(教育部的高官們和實際接觸學童的老師)自己的人格, 作人處事都沒學好, 怎麼去教小朋友呢? 說真的, 小孩子會變壞, 都是大人的責任.\n\n 所以我決定要親身投入, 相信有我的投入, 不只我的小寶貝, 您的寶貝也會有所不同.",
    "online" : false,
    "rowid" : "",
    "share" : "數學;物理;化學;體育",
    "site" : "http://homelandkid.wix.com/homelandkid",
    "site2" : "http://homelandkid.wix.com/homelandkid",
    "username" : "vincentgotu",
    "時間戳記" : "2013/11/7 下午 7:01:59"
  }, {
    "Style" : "large_red",
    "address" : "新北市新店區花園一路",
    "ask" : "無",
    "connect_me" : "http://bojne20130903.blogspot.tw/",
    "hometown" : "undefined",
    "id" : "100000689706285",
    "latlngColumn" : "24.934448,121.555206",
    "learner_birth" : "1999",
    "learner_habit" : "自然、生態",
    "learner_role" : "自學生",
    "learner_type" : "團體共學",
    "name" : "黃岳涵",
    "note" : "赤皮仔自學團學生。\n從國中二年級開始自學。",
    "online" : false,
    "share" : "無",
    "site" : "http://bojne20130903.blogspot.tw/",
    "site2" : "http://bojne20130903.blogspot.tw/",
    "username" : "bojne.john",
    "時間戳記" : "2014/1/18 下午 10:55:31"
  }, {
    "Style" : "large_red",
    "address" : "宜蘭縣三星鄉泰雅一路215巷清水292號",
    "ask" : "分享教學資源",
    "child_birth" : "1997",
    "child_birth2" : "2000",
    "connect_me" : "joeyliaw.tw@gmail.com",
    "hometown" : "Taichung, Taiwan",
    "id" : "1797537878",
    "latlngColumn" : "24.66863,121.662891",
    "learner_birth" : "1968",
    "learner_habit" : "資訊",
    "learner_role" : "自學家長",
    "learner_type" : "團體共學",
    "name" : "廖修毅",
    "note" : "我是個退伍軍人，在體制外學校也擔任過國中部總導師，我知道教育對下一代的重要，因此想要在這個領域繼續投入。",
    "online" : false,
    "share" : "如何自學",
    "site" : "http://joeyliaw.blogspot.tw/",
    "site2" : "http://www.qsteens-edu.com/",
    "username" : "joeyliaw.tw",
    "時間戳記" : "2014/1/23 下午 10:11:18"
  }, {
    "address" : "台北市",
    "connect_me" : "hsinyi.ok@gmail.com",
    "hometown" : "undefined",
    "id" : "100001272594692",
    "latlngColumn" : "25.0374,121.56355",
    "learner_role" : "獨立教育工作者",
    "name" : "邱欣怡",
    "note" : "我喜歡有大自然的地方^^\n喜歡在生活空間種植作物～",
    "share" : "樸門生活實作、野菜、藥草、種植作物、烹飪、經絡按摩、QHHT(量子回溯療癒)",
    "site" : "www.facebook.com/hsinyi.ok",
    "username" : "hsinyi.ok"
  }, {
    "address" : "大台北",
    "connect_me" : "教學二十年極具熱忱的飛揚老師\n歡迎一對一和小班紮根教學邀約\nhappyfranz@gmail.com",
    "id" : "100005949522494",
    "latlngColumn" : "25.085956,121.561474",
    "learner_role" : "獨立教育工作者",
    "learner_type" : "個人",
    "name" : "Franz Yang",
    "note" : "我是二十年保持教育熱忱的良心教育家~飛揚老師，台大建築研究所畢，曾有兩本作文著作在市面上發行，學生超過十萬人次，有六個家庭追著老師學習直到畢業。\n\n以社會價值最在意的成績競爭力來說：\n 1.自己：高中榜首畢業，台大榜首進研究所（只是想站在一個明顯的社會位置，提出放下惡行競爭，要求友善合作的良性競爭，創造多贏）\n\n2.學生升上台清交大，包涵聯考成績進步九千名，高中升大學數理雙料滿分，國際交換留學生榜首，以及畢業進入建中、北一女各校的學生（只想印證不靠死讀書，不只限紙筆測驗，好好紮實磨練生活能力，轉換到學習一樣有競爭力）\n\n3.目前學生多位在美國紐約、法國、德國發展，台灣學生大量成為各學校領導幹部（會讀會玩會服務，才是真實力， 才有與社會接軌的待人處世能力）\n\n擅長教學領域：\n 1.溝通與文學寫作\n2.道地英語發音與英語學習\n3.情境數學\n4.繪畫饗宴\n5.心理諮詢、學習弱點診斷、生涯分析\n6.寫作、兒童心理、適性的班級管理師資培訓\n\n教學理念\n1.學生一定要受教（自由意志無法勉強），才能教。\n\n2.學生受教力與家長榜樣習習相關，良性尊重的親師合作是教學成果豐碩的前提。\n\n3.缺乏學習興趣的孩子是因為內在受傷，只要父母願給孩子時間療癒，給老師空間發揮，必能重拾學習興趣。\n\n4.我曾受的訓練包括：台大中等教育學程、開放教育~雅德賽思、補救教育~艾菲爾、學療教育~ 蒙特梭利、華德福教育、作文、英文、數學科師資培訓，以及藝術、園藝、戲劇、個人中心與家族心理治療，因此教學重視量身打造、靈活運用。\n\n5.教學現場充滿笑聲，或者奮鬥的氣息，或者對各領域自然觀察的驚嘆，除了教師的功力外，家長的支持與鼓勵以及不吹毛求疵，也是成功因素。\n\n願與有緣人一起用心耕耘，讓學習成為生命的饗宴～飛揚老師",
    "share" : "寫作、英文、數學、繪畫、溝通表達、心理諮詢、生涯規劃",
    "site" : "https://www.facebook.com/franz.yang.71",
    "username" : "franz.yang.71"
  }, {
    "address" : "新竹縣竹東鎮下公館",
    "ask" : "木工的工具和師傅",
    "connect_me" : "",
    "freetime" : "週一、週三。週末。",
    "hometown" : "Taipei, Taiwan",
    "id" : "1755202221",
    "invis" : false,
    "latlngColumn" : "24.7229,121.09577",
    "learner_birth" : "1977",
    "learner_habit" : "看書、電影、織毛線、自創料理",
    "learner_role" : "獨立教育工作者",
    "learner_type" : "三五好友",
    "name" : "高毓惠",
    "note" : "獨立教育工作者。超喜歡和小孩一起玩，也喜愛和青少年聊天談夢想或生活中的困惑與煩惱。   \n\n之前曾在兩間理念學校任教（全人中學、道禾實驗學校），未來志業是致力於增進人以及土地的幸福。\n\n目前在新竹市和竹東鎮帶領國小的課後共學團體。",
    "online" : false,
    "share" : "科學實驗活動、國小年紀孩童創意激發與藝術創作",
    "site" : "http://blog.roodo.com/yuhuikao",
    "site2" : "https://www.facebook.com/groups/124778894387483/",
    "username" : "yuhui.kao.7"
  }, {
    "address" : "台北市信義區吳興街",
    "connect_me" : "",
    "followBy" : [ 63 ],
    "hometown" : "Taipei, Taiwan",
    "id" : "1589052394",
    "latlngColumn" : "25.0263529,121.564975",
    "learner_habit" : "英文，西班牙文，瑜珈，旅行，身心靈，動物",
    "learner_role" : "自學家長",
    "learner_type" : "個人",
    "name" : "Jaline Chiu",
    "note" : "打算女兒小一時讓她自學，想多認識附近有自學的家長，可以一起共學交流，謝謝。",
    "share" : "英文，西班牙文，法文，瑜珈，",
    "site" : "https://www.facebook.com/jaline.chiu",
    "site2" : "",
    "username" : "jaline.chiu"
  }, {
    "address" : "台北市大安區敦化南路",
    "connect_me" : "jacker21066@gmail.com",
    "id" : "1196276522",
    "latlngColumn" : "25.03635,121.548775",
    "learner_role" : "自學生",
    "learner_type" : "三五好友",
    "name" : "金詩晨",
    "note" : "你好我是傑克 \n\n十七歲開始自學  \n現在即將滿二十一歲 剛開始工作",
    "share" : "對新創舉的支持討論和關注",
    "site" : "https://www.facebook.com/jacker2106",
    "username" : "jacker2106"
  }, {
    "address" : "台北市明水路397巷",
    "id" : "100001730506297",
    "latlngColumn" : "25.078356,121.547699",
    "learner_habit" : "電腦、烹飪",
    "learner_role" : "自學家長",
    "learner_type" : "個人",
    "name" : "Hcy Csy",
    "note" : "我有兩個小孩從2014年2月開始自學，哥哥高一，興趣電腦資訊，弟弟國二，興趣烹飪旅遊運動，希望參加本社團能多認識一些朋友，經驗交流。",
    "share" : "自學初體驗中",
    "site" : "https://www.facebook.com/csyhcy",
    "username" : "csyhcy"
  }, {
    "address" : "台北市萬華區",
    "hometown" : "Taipei, Taiwan",
    "id" : "1465994756",
    "latlngColumn" : "25.03528,121.49963",
    "learner_role" : "自學家長",
    "name" : "呂柏志",
    "note" : "是基督徒，目前在台北市召會2會所聚會，有一個三個月大的女寶(2013.11生)",
    "online" : false,
    "share" : "場地、社會科學類知識，聖經知識",
    "site" : "https://www.facebook.com/POKILU2011",
    "username" : "POKILU2011"
  }, {
    "address" : "新北市新店區安民街",
    "ask" : "",
    "child_birth" : "2006",
    "child_birth2" : "2008",
    "connect_me" : "",
    "followBy" : [ 72 ],
    "hometown" : "undefined",
    "id" : "100000239876768",
    "invis" : false,
    "latlngColumn" : "24.971689,121.51712",
    "learner_birth" : "1973",
    "learner_habit" : "",
    "learner_role" : "自學家長",
    "learner_type" : "個人",
    "name" : "陳慧中",
    "note" : "帶著三個孩子在家自學,\n以閱讀教會經文,讀經,作家事為自學主軸,\n加上學校的數學科目及不定期出遊",
    "share" : "經驗交流",
    "site" : "https://www.facebook.com/jtk123",
    "site2" : "",
    "username" : ""
  }, {
    "address" : "台北市中山區建國北路二段151巷",
    "id" : "1124892690",
    "latlngColumn" : "25.061806,121.537521",
    "learner_role" : "自學家長",
    "learner_type" : "個人",
    "name" : "Li-Ying Fu",
    "note" : "老大小一, 對各領域都很有興趣, 若有機會希望能與附近年齡相近的自學生交流",
    "share" : "語文領域",
    "site" : "https://www.facebook.com/liying.fu.3",
    "username" : "liying.fu.3"
  }, {
    "address" : "新北市板橋區站前路",
    "ask" : "互助生活學習夥伴, 自然生活的學習資源",
    "connect_me" : "fridaywutw@hotmail.com",
    "id" : "1317087484",
    "latlngColumn" : "25.015221,121.463592",
    "learner_habit" : "自然生活、學習研究、自由創作",
    "learner_role" : "自學生",
    "learner_type" : "三五好友",
    "name" : "Friday Wu",
    "note" : "自學生、獨立教育工作者、自學家長。\n在嘗試錢以外的自然生活方式，向自然學習、民族與傳統智慧學習、向開放但有自我節制的心學習",
    "share" : "自然生活、教育訓練、自由創作",
    "site" : "https://www.facebook.com/friday.wu.1",
    "username" : "friday.wu.1"
  }, {
    "address" : "高雄市三民區天民路26號",
    "connect_me" : "0920352663\n0929217423",
    "freetime" : "全日",
    "hometown" : "Fengshan, Taiwan",
    "id" : "1495163388",
    "latlngColumn" : "22.64364,120.345352",
    "learner_role" : "自學家長",
    "learner_type" : "三五好友",
    "name" : "鄭得恩",
    "note" : "我教樂團，我傳福音，我很判逆，我也傳統，我教才藝，更帶生命；我喜歡連結各式各樣的領域，發展拓展多元化、寬廣無止盡的福音管道，帶領培養教育具有影響力的青年，成為影響世界、國家、社會、校園、家庭的基督徒\n\n若您要加好友，請傳訊告知您的教會或機構…\n\n最怕沒有勇氣和異象的人，\n我很衝，也很靜，衝突嗎？\n不，有異象就會成就不平凡的未來。\n\n你願意參與神在祂國度中的事工嗎？歡迎您索取代禱信，與我們一起同工。《若您願意參與這樣的事工，敬請告知您的收件地址或E-MAIL，讓我們可以將教會的發展與成長用mail寄給您。》\n如何到提摩太教會\n先搭乘捷運橘線至衛武營站(O10)， 再搭乘高雄市公車70號至「澄清路站」下車，往麥當勞方向走，右轉天民路即可看見提摩太教會。",
    "share" : "各類，實務操作，農園操作等",
    "site" : "https://www.facebook.com/deran.cheng",
    "username" : "deran.cheng"
  }, {
    "address" : "台北市內湖區康寧路一段",
    "ask" : "",
    "connect_me" : "",
    "freetime" : "平日",
    "hometown" : "undefined",
    "id" : "742883665",
    "invis" : false,
    "latlngColumn" : "25.079016,121.594544",
    "learner_habit" : "科學，中英文學習",
    "learner_role" : "自學家長",
    "learner_type" : "三五好友",
    "name" : "Jenny Wilkins",
    "note" : "An ESL teacher and am raising two bilingual kids.  Interested in bilingual education and making more friends in the home school community!",
    "share" : "coding, science, and bilingual studies",
    "site" : "https://www.facebook.com/jenny.wilkins.712",
    "site2" : "",
    "username" : "jenny.wilkins.712"
  }, {
    "address" : "雲林縣林內鄉新興路81號",
    "ask" : "如何開始",
    "connect_me" : "0980823386",
    "hometown" : "Taichung, Taiwan",
    "id" : "100000099165177",
    "latlngColumn" : "23.761391,120.61451",
    "learner_role" : "自學家長",
    "learner_type" : "三五好友",
    "name" : "Pâng Tông-Kîong",
    "note" : "我是巧大，巧大是我\n一生一世跟隨主\n一生一世學基督\n一生一世傳福音\n一生一世行天路\n\n遇見耶穌復活的大能\n萬事都會變成可能\n\n\n社團法人雲林縣愛加倍愛家協會社工兼總幹事",
    "share" : "經驗談",
    "site" : "https://www.facebook.com/pangtongkiong",
    "username" : "pangtongkiong"
  }, {
    "address" : "台北市中山區復興北路",
    "ask" : "暫無",
    "child_birth" : "1989",
    "child_birth2" : "2001",
    "connect_me" : "https://www.facebook.com/hsu.mark.52",
    "freetime" : "週日",
    "id" : "100000922094333",
    "latlngColumn" : "25.048676,121.543838",
    "learner_birth" : "1962",
    "learner_habit" : "不可說",
    "learner_role" : "自學家長",
    "learner_type" : "個人",
    "name" : "Mark Hsu",
    "note" : "Mark",
    "online" : false,
    "share" : "暫無",
    "site" : "https://www.facebook.com/hsu.mark.52",
    "site2" : "暫無",
    "username" : "hsu.mark.52"
  }, {
    "address" : "新北市三重區仁愛街278號6F",
    "child_birth" : "2008",
    "child_birth2" : "2010",
    "freetime" : "一,三,四平日",
    "hometown" : "Ilan, T'Ai-Wan, Taiwan",
    "id" : "100000132174757",
    "latlngColumn" : "25.07904,121.492538",
    "learner_birth" : "1979",
    "learner_role" : "自學家長",
    "learner_type" : "團體共學",
    "name" : "Joy Faith",
    "note" : "我們家有2個寶貝,大寶貝5Y4M,小寶貝3Y3M,目前朝向自學路邁進,希望認識更多已走在這條路上的朋友們,彼此學習,成長!",
    "share" : "生活大小事",
    "site" : "https://www.facebook.com/joy.faith.7",
    "username" : "joy.faith.7"
  }, {
    "address" : "台北士市中山區",
    "ask" : "數學與空間邏輯",
    "child_birth" : "2005",
    "child_birth2" : "2007",
    "connect_me" : "手機或簡訊\n0928 225 135",
    "freetime" : "平日白天",
    "hometown" : "Taipei, Taiwan",
    "id" : "100001076986262",
    "latlngColumn" : "25.085956,121.561474",
    "learner_role" : "自學家長",
    "learner_type" : "個人",
    "name" : "Pamela Chiang",
    "note" : "我婚前任職於外國金融機構長期定居於國外，為了6歲的孩子遷居回台；目前為全職且全心陪伴小孩。",
    "share" : "英語教學與海外居住經驗",
    "site" : "htts://www.facebook.com/pamela.chiang.79",
    "username" : "pamela.chiang.79"
  }, {
    "address" : "板橋江子翠",
    "ask" : "戶外伴遊",
    "child_birth" : "2006",
    "child_birth2" : "2009",
    "freetime" : "周二、周四",
    "hometown" : "Taipei, Taiwan",
    "id" : "1647458428",
    "latlngColumn" : "25.02989,121.472282",
    "learner_birth" : "1980",
    "learner_role" : "自學家長",
    "learner_type" : "三五好友",
    "name" : "Leia Weng",
    "note" : "我是家教老師，周間帶女兒自學。兩個女兒一個一年級，一個小班，希望能認識志同道合的同伴。",
    "share" : "數理、樂高",
    "site" : "https://www.facebook.com/leia.weng",
    "username" : "leia.weng"
  }, {
    "address" : "新北市永和區永和路二段425巷56號",
    "ask" : "",
    "connect_me" : "kevin78515@gmail.com",
    "freetime" : "星期一星期六",
    "hometown" : "Kaohsiung, Taiwan",
    "id" : "1448347314",
    "invis" : false,
    "latlngColumn" : "25.017481,121.513863",
    "learner_birth" : "1989",
    "learner_habit" : "程式設計",
    "learner_role" : "獨立教育工作者",
    "learner_type" : "個人",
    "name" : "束凱文",
    "note" : "我的興趣是程式語言與教育，目前任職引號科技，請多多指教～ :)",
    "online" : false,
    "share" : "程式設計、理化",
    "site" : "https://www.facebook.com/kaiwen.shu",
    "site2" : "",
    "username" : "kaiwen.shu"
  }, {
    "address" : "台東市",
    "ask" : "",
    "child_birth" : "2009",
    "child_birth2" : "2011",
    "connect_me" : "finchen@gmail.com",
    "freetime" : "週間晚上",
    "hometown" : "Taichung, Taiwan",
    "id" : "1181607134",
    "latlngColumn" : "22.75487,121.14646",
    "learner_birth" : "1979",
    "learner_habit" : "",
    "learner_role" : "自學家長",
    "learner_type" : "個人",
    "name" : "Finn Chen",
    "note" : "近期即將搬往台東, 希望能與在美麗東部的自學家庭或獨立教育工作者多認識多交流, 建立這邊的學習資源",
    "share" : "繪本朗讀, 英語學習",
    "site" : "https://www.facebook.com/finn.chen",
    "site2" : "",
    "username" : "finn.chen"
  }, {
    "address" : "台中市龍井區遠東街",
    "ask" : "",
    "child_birth" : "2007",
    "connect_me" : "",
    "freetime" : "all",
    "hometown" : "Changhua",
    "id" : "100000648997757",
    "latlngColumn" : "24.190861,120.58857",
    "learner_birth" : "1975",
    "learner_habit" : "",
    "learner_role" : "自學家長",
    "learner_type" : "個人",
    "name" : "Mina Ko",
    "note" : "小孩自今年小一下開始自學.....\n希望能尋找相近年齡的互動課程",
    "share" : "數理及實驗方面",
    "site" : "https://www.facebook.com/mina.ko.9",
    "site2" : "",
    "username" : "mina.ko.9"
  }, {
    "address" : "台北市信義區忠孝東路四段559巷",
    "ask" : "",
    "child_birth" : "2004",
    "child_birth2" : "2005",
    "connect_me" : "fb留言",
    "freetime" : "晚上和周末",
    "hometown" : "undefined",
    "id" : "1511986251",
    "latlngColumn" : "25.041491,121.563637",
    "learner_birth" : "",
    "learner_habit" : "",
    "learner_role" : "自學家長",
    "learner_type" : "個人",
    "name" : "Sophie Wu",
    "note" : "希望可以在開放式的學習環境中，藉由有系統的引導及探索，培養出主動積極的學習態度和思考解決問題的能力，並將學習活化，讓孩子可將所學的知識與能力廣泛應用於日常生活中。另外也希望可以透過客製化的課程，有更多的時間彈性，進行多國語言的學習，培養孩子世界觀。",
    "online" : false,
    "share" : "英語學習分享",
    "site" : "https://www.facebook.com/sophie.scwu",
    "site2" : "https://www.facebook.com/pages/%E4%B8%BB%E9%A1%8C%E5%BC%8F%E9%9B%99%E8%AA%9E%E5%AF%A6%E9%A9%97%E6%95%99%E8%82%B2/186489618181846",
    "username" : "sophie.scwu"
  }, {
    "address" : "台北市內湖區",
    "ask" : "經驗交流",
    "connect_me" : "臉書\nemail：yunegh@gmail.com",
    "freetime" : "周間下午晚上",
    "hometown" : "undefined",
    "id" : "100000066362428",
    "invis" : false,
    "latlngColumn" : "25.0691,121.58848",
    "learner_birth" : "1987",
    "learner_habit" : "",
    "learner_role" : "自學生 + 獨立教育工作者",
    "learner_type" : "三五好友",
    "name" : "Yunegh Hsieh",
    "note" : "目前在寫自我敘說的論文，慢慢整理這幾年在獵人學校的學習與看見，並與自己的生命經驗對照，希望能夠讓更多人看到這片土地的價值和我們自己的美好!:)",
    "share" : "諮商輔導、國中、小數學學習、爬山",
    "site" : "https://www.facebook.com/shanshan.hsieh",
    "site2" : "",
    "username" : ""
  }, {
    "address" : "台南市",
    "ask" : "自學經驗，資源資訊",
    "child_birth" : "2009",
    "child_birth2" : "2013",
    "connect_me" : "E-mail: inkiyclin@gmail.com",
    "freetime" : "平日早上",
    "id" : "1248424930",
    "latlngColumn" : "22.99122,120.18496",
    "learner_birth" : "1976",
    "learner_habit" : "料理，電影，露營，旅遊，畫圖，閱讀，等等....",
    "learner_role" : "自學家長",
    "learner_type" : "類學校機構",
    "name" : "Inki Hayashi",
    "note" : "大家好！我是個專職媽媽，超愛旅遊，料理/烘培，彩畫，閱讀等等。家有老公和兩個兒子，老公工作忙碌，我在家自己帶小孩。老大今年五歲，已上幼稚園中班（我們幼稚園是混齡班的），很好動，動作大，不太能約束（但也不是講不通），很有自己的意見和看法，也很有創意，很聰明，跟「一般」的孩子不太一樣，很有個性。對他，我真覺得他可愛，可氣，又可笑。他每天磨練我的耐心和寬度！但也有很甜蜜的一面，常常讓我氣後不得不原諒他。有了他，我的每天實在很精彩，不會無聊！（太忙了點兒...）小兒子九個月大，個性和哥哥不太一樣，溫和乖巧，很會自得取樂，吃飽喝飽換好就可以心情好地自己啊啊嗚嗚講個不停，很愛笑，但也是個很有個性，很堅持的小孩。\n\n最近因為大兒子的特性，也因為明年他就要上小學的年齡，我開始思考「上學」這件事，並開始尋找對他最適合的教育模式。台灣的學校教育感覺好像都要把每一個小孩放進一個模範盒子裡，如果「溢出來」好像就被貼「異常」或是「不乖巧」等等標籤（注：這只是我的印象），我大兒子又是那種大人認為「白目」，「調皮」類的小孩。我不希望他在這樣的眼光下受不好的影響。且，在這樣的制度裡，連我們自己都會受影響，對我們的影響，很容易會影響小孩。我希望我可以珍惜他的特質並學習引導他走屬於他的道路。\n\n另外小學後又很多課業，且好像常常為了考試而考試，學習好像都是因為考試，有點本末倒置。每次看到補習班外面貼上誰誰誰考上某某某好大學等等的跑燈及看覽板就覺得好空虛。我認為教育本身是為了學習，擴大我們對世界的了解，培養我們追求真理的心，最重要的是在這過程中幫助孩子成為神中用的人的同時，我自己也能成長並榮耀神的名，而不是為了炫耀自己考試有多厲害，上了哪間好了不起的大學。考試技巧好，但沒有思考能力是很可悲的。\n\n至於homeschooling這一方面，我知道國外已經很成熟，也有很多資源與互相支持的制度，因為我姊姊也是homeschooling的經驗者。但，在台灣，我不知道這一方面是否已成熟，尤其是在南部，也不知道從哪裡著手好。所以歡迎並感謝有經驗的父母朋友們和我分享您們的經驗讓我參考。也希望若有什麼活動，我也想帶著孩子們去參加看看！請多多指教，謝謝！",
    "share" : "英文，日文會話，烘培/料理教學",
    "site" : "http://lin2babies.pixnet.net/blog",
    "site2" : "",
    "username" : "InkyPinky109"
  }, {
    "address" : "台中市西屯區黎明路三段",
    "ask" : "",
    "connect_me" : "",
    "freetime" : "星期一至星期五下午",
    "hometown" : "Kaohsiung, Taiwan",
    "id" : "100000245251124",
    "latlngColumn" : "24.18335,120.63942",
    "learner_birth" : "1073",
    "learner_habit" : "",
    "learner_role" : "自學生家長",
    "learner_type" : "三五好友",
    "name" : "趙雪汝",
    "note" : "我有3個小孩，目前國三、小六、大班，剛好正在經歷不同的求學階段，累積了一些經驗，願與大家分享！",
    "share" : "每週三帶孩子課後小旅行",
    "site" : "https://www.facebook.com/profile.php?id=100000245251124",
    "site2" : "",
    "username" : ""
  }, {
    "address" : "台北市士林區天母東路43巷",
    "ask" : "",
    "connect_me" : "0935066447\nkaxanote@gmail.com",
    "freetime" : "週四~週五白天",
    "hometown" : "Taichung, Taiwan",
    "id" : "810475366",
    "latlngColumn" : "25.11832,121.532372",
    "learner_birth" : "1973",
    "learner_habit" : "解題",
    "learner_role" : "獨立教育工作者",
    "learner_type" : "個人",
    "name" : "陶倢",
    "note" : "我可以分享國高中數學理化的學習經驗，並給予學生引導，也可以免費幫自學孩子利用line或其他通訊軟體免費解題",
    "share" : "國高中數理問答",
    "site" : "https://www.facebook.com/profile.php?id=810475366",
    "site2" : "",
    "username" : ""
  }, {
    "address" : "桃園大竹.宜蘭三星鄉",
    "ask" : "",
    "child_birth" : "2001",
    "child_birth2" : "2004",
    "connect_me" : "alivivi687@kimo.com",
    "id" : "100004109468111",
    "latlngColumn" : "24.66863,121.662891",
    "learner_birth" : "1971",
    "learner_habit" : "閱讀、DIY、烹飪、舞蹈",
    "learner_role" : "自學家長",
    "learner_type" : "個人",
    "name" : "令意",
    "note" : "周一~周五住在宜蘭，以前從事家政勞作教材設計工作，目前帶著小女兒自學，大女兒於清水小校共學，希望能多交一些朋友。",
    "share" : "家政勞作、烹飪",
    "site" : "https://www.facebook.com/profile.php?id=100004109468111",
    "site2" : "",
    "username" : ""
  }, {
    "address" : "台中市南區五權南路",
    "ask" : "",
    "connect_me" : "0989-962903",
    "freetime" : "在家工作者，時間彈性",
    "hometown" : "Kaohsiung, Taiwan",
    "id" : "1452500669",
    "latlngColumn" : "24.122656,120.670082",
    "learner_birth" : "1979",
    "learner_habit" : "攝影",
    "learner_role" : "自學家長",
    "name" : "李仲翔",
    "note" : "蒐集資料，考慮自學的家長",
    "share" : "影片製作",
    "site" : "https://www.facebook.com/owl2903.videa",
    "site2" : "",
    "username" : "owl2903.videa"
  }, {
    "address" : "新北市新店區秀山路",
    "ask" : "",
    "connect_me" : "jiyi@jiyi.co.uk <br>\njiyi@istscare.org",
    "freetime" : "",
    "id" : "1570774650",
    "latlngColumn" : "24.95989,121.530739",
    "learner_birth" : "1983",
    "learner_habit" : "物理、原分子科學、數學、計算機科學、性別",
    "learner_role" : "教師、自學生",
    "learner_type" : "三五好友",
    "name" : "Jiyi Ng",
    "note" : "我吳芷儀，可以叫我小芷。身份是獨立教師與自學生，每個人都可以是我的老師，我也可以是每個人的學生，彼此互相學習。領域是物理、數學、計算機、性別。我想組個跨領域的讀書會，讓學習不受大學所屬科系限制，每個人都能自由自主快樂學習。",
    "share" : "物理、數學、計算機科學、性別",
    "site" : "https://www.facebook.com/apjiyi",
    "site2" : "facebook.com/groups/beyondgender",
    "username" : "apjiyi"
  }, {
    "address" : "宜蘭縣頭城鎮公園路",
    "ask" : "孩子們的玩伴、自學經驗分享",
    "child_birth" : "2002",
    "child_birth2" : "2006",
    "connect_me" : "ally8888@gmail.com\nFB訊息",
    "id" : "1048769170",
    "latlngColumn" : "24.859856,121.820396",
    "learner_birth" : "1968",
    "learner_habit" : "手作（拼布、手工皂）",
    "learner_role" : "自學家長",
    "name" : "Chang LiLi",
    "note" : "我們四年前搬來宜蘭，目前一個在人文國小，一個在中山國小就讀",
    "share" : "思想",
    "site" : "https://www.facebook.com/lili.chang.90",
    "site2" : "",
    "username" : "lili.chang.90"
  }, {
    "address" : "台中市西屯區惠文七街",
    "ask" : "自然與藝術領域",
    "child_birth" : "2005",
    "child_birth2" : "2006",
    "connect_me" : "0937779607",
    "freetime" : "周一,周三,和周五上午",
    "hometown" : "Taichung, Taiwan",
    "id" : "1622174786",
    "latlngColumn" : "24.156572,120.637482",
    "learner_birth" : "1976",
    "learner_habit" : "",
    "learner_role" : "自學家長",
    "learner_type" : "個人",
    "name" : "林孟俞",
    "note" : "曾是國小英語教師,目前專心在家自學教導孩子,孩子專長是圍棋與捏塑!",
    "share" : "English & Go",
    "site" : "https://www.facebook.com/mengyu.lin.549",
    "site2" : "",
    "username" : "mengyu.lin.549"
  }, {
    "address" : "雲林縣崙背鄉港尾村新鎮路3/7號",
    "ask" : "",
    "connect_me" : "lkm6963157@gmail.com",
    "freetime" : "隨時",
    "id" : "100001865270351",
    "latlngColumn" : "23.755426,120.376869",
    "learner_birth" : "1962",
    "learner_habit" : "閱+歷",
    "learner_role" : "獨立教育工作者",
    "learner_type" : "個人",
    "name" : "猛辣孟申",
    "note" : "我是廖坤猛\n阿猛哥\n猛辣孟申，阿猛\n煞猛後生",
    "share" : "猛辣孟申的教育理念",
    "site" : "https://www.facebook.com/lkm0921351020",
    "site2" : "虎尾社造中心",
    "username" : "lkm0921351020"
  }, {
    "address" : "新北市新店區",
    "ask" : "",
    "child_birth" : "1999",
    "child_birth2" : "2005",
    "connect_me" : "26669092",
    "freetime" : "星期二",
    "id" : "100000179266448",
    "latlngColumn" : "24.936701,121.528999",
    "learner_birth" : "1971",
    "learner_habit" : "社會學",
    "learner_role" : "自學家長、自學老師",
    "learner_type" : "團體共學",
    "name" : "鄭婉琪",
    "note" : "我是赤皮仔自學團的老師",
    "share" : "組織想法",
    "site" : "https://www.facebook.com/wangi100",
    "site2" : "",
    "username" : "wangi100"
  }, {
    "address" : "基隆市暖暖區東勢街",
    "ask" : "希望找到對自學有興趣的家長組成團體",
    "child_birth" : "2012",
    "connect_me" : "",
    "freetime" : "週一到週五白天",
    "id" : "720125722",
    "latlngColumn" : "25.087978,121.743164",
    "learner_birth" : "1976",
    "learner_habit" : "",
    "learner_role" : "自學家長",
    "learner_type" : "個人",
    "name" : "詠澤",
    "note" : "其實我的小朋友還不到兩歲，但是基於對制式教育缺乏信心及認同，希望能在基隆組成自學團體，與理念相近的父母交流合作，謝謝！",
    "share" : "聚會空間、資訊交流、書籍交換",
    "site" : "https://www.facebook.com/yungtse",
    "site2" : "",
    "username" : "yungtse"
  }, {
    "address" : "新北市三重區",
    "ask" : "兒童心理  課程設計",
    "connect_me" : "FB",
    "freetime" : "週三早上",
    "hometown" : "Taipei, Taiwan",
    "id" : "100004454673555",
    "latlngColumn" : "25.054501,121.469002",
    "learner_birth" : "1977",
    "learner_habit" : "閱讀 健行",
    "learner_role" : "獨立教育工作者",
    "learner_type" : "個人",
    "name" : "陳奕蓁",
    "note" : "身兼阿姨與家庭教師身份的我，面對三歲，八歲，九歲的三個孩子，希望真正能幫助他們健康快樂的長大～",
    "share" : "數學 英語 排球 吉他",
    "site" : "https://www.facebook.com/yijhen.chen.395",
    "site2" : "",
    "username" : "yijhen.chen.395"
  }, {
    "address" : "新北市中和區忠孝街19巷41號",
    "ask" : "",
    "child_birth2" : "2010",
    "connect_me" : "",
    "hometown" : "Taipei, Taiwan",
    "id" : "100000349232889",
    "latlngColumn" : "24.98489,121.509491",
    "learner_birth" : "1981",
    "learner_habit" : "烘焙",
    "learner_role" : "自學家長",
    "learner_type" : "三五好友",
    "name" : "林芫蓉",
    "note" : "林芫蓉",
    "share" : "手工藝",
    "site" : "https://www.facebook.com/profile.php?id=100000349232889",
    "site2" : "",
    "username" : ""
  }, {
    "address" : "新北市樹林區學府路",
    "ask" : "",
    "child_birth" : "2010",
    "connect_me" : "",
    "freetime" : "平日白天",
    "id" : "1320158554",
    "latlngColumn" : "24.951292,121.385056",
    "learner_birth" : "1971",
    "learner_habit" : "",
    "learner_role" : "自學家長",
    "learner_type" : "團體共學",
    "name" : "Maggie Lo",
    "note" : "我有一個三歲多的女兒, 目前讓她參加兒童律動, 畫畫課還有兒童讀經班.",
    "share" : "弟子規學習",
    "site" : "https://www.facebook.com/maggie.lo.73",
    "site2" : "",
    "username" : "maggie.lo.73"
  }, {
    "address" : "高雄市鼓山區",
    "ask" : "",
    "connect_me" : "anne4school@gmail.com",
    "freetime" : "週一、五（高三生要乖乖念書...）",
    "hometown" : "undefined",
    "id" : "100000159758208",
    "invis" : false,
    "latlngColumn" : "22.63676,120.2809",
    "learner_birth" : "1996",
    "learner_habit" : "塗鴉、音樂、模聯、游泳",
    "learner_role" : "自學生",
    "learner_type" : "個人",
    "name" : "郭沐恩",
    "note" : "來自基督徒家庭\n目前報考SAT\n並繼續念高三上課程和準備學測\n歡迎年齡相近的朋友一起讀書交流!",
    "online" : false,
    "share" : "英文",
    "site" : "https://www.facebook.com/anneoct27",
    "site2" : "",
    "username" : ""
  }, {
    "address" : "新北市新莊區",
    "ask" : "上課資訊交流",
    "child_birth" : "2004",
    "child_birth2" : "2010",
    "connect_me" : "",
    "freetime" : "平日下午",
    "hometown" : "Taipei, Taiwan",
    "id" : "1774611916",
    "latlngColumn" : "25.03568,121.45046",
    "learner_birth" : "1973",
    "learner_habit" : "步道、賞鳥",
    "learner_role" : "自學家長",
    "learner_type" : "三五好友",
    "name" : "Cindy Chen",
    "note" : "希望能認識更多自學生、團體，讓孩子交友圈更廣，並且有更多資訊交流的機會",
    "online" : false,
    "share" : "介紹社團、老師",
    "site" : "https://www.facebook.com/profile.php?id=1774611916",
    "site2" : "",
    "username" : ""
  }, {
    "address" : "竹東鎮麥當勞附近",
    "ask" : "學伴",
    "child_birth" : "2010",
    "child_birth2" : "2013",
    "connect_me" : "fb帳號 Yuju Chen",
    "freetime" : "周一~周五 am9~pm5",
    "hometown" : "Hualien City",
    "id" : "100000210002938",
    "latlngColumn" : "24.72169,121.074649",
    "learner_birth" : "1980",
    "learner_habit" : "",
    "learner_role" : "自學家長",
    "learner_type" : "個人",
    "name" : "Yuju Chen",
    "note" : "我是全職媽, 家中兩位小孩都是女孩,平時在家讓孩子從事靜態的活動,偶爾外出在竹東住家附近散步,騎單車或至圖書館挖寶.想幫三歲半孩子找學(玩)伴,讓孩子一起(學)玩,媽媽可以交流分享生活",
    "share" : "說故事",
    "site" : "https://www.facebook.com/yuju.chen.714",
    "site2" : "",
    "username" : "yuju.chen.714"
  }, {
    "address" : "台北市內湖路一段",
    "ask" : "",
    "connect_me" : "",
    "freetime" : "平日晚間",
    "id" : "665153197",
    "latlngColumn" : "25.0846,121.560554",
    "learner_birth" : "1985",
    "learner_habit" : "",
    "learner_role" : "獨立教育工作者",
    "learner_type" : "團體共學",
    "name" : "Nancy Lan",
    "note" : "目前為赤皮仔自學團的教師,擔任自然科老師和九年級導師的工作!",
    "share" : "國中數理科,生物",
    "site" : "https://www.facebook.com/nancy.lan.108",
    "site2" : "http://teenedu.pixnet.net/blog",
    "username" : "nancy.lan.108"
  }, {
    "address" : "台北市大安區羅斯福路三段",
    "ask" : "",
    "connect_me" : "",
    "freetime" : "地點靠近台大/師大<br>\n星期三四之外的白天",
    "id" : "1699315280",
    "latlngColumn" : "25.021721,121.527031",
    "learner_birth" : "1978",
    "learner_habit" : "",
    "learner_role" : "自學家長",
    "name" : "Vicky Chen",
    "note" : "全職媽媽帶1歲半的寶寶，想要找志同道合，可以一起育兒，讓孩子有伴，或者PG之類的可能",
    "share" : "作文",
    "site" : "https://www.facebook.com/vicky415",
    "site2" : "",
    "username" : "vicky415"
  }, {
    "address" : "新北市板橋區文化路二段",
    "ask" : "",
    "connect_me" : "peifen1118@yahoo.com.tw",
    "followBy" : [ 73 ],
    "freetime" : "週五下午",
    "id" : "550617967",
    "latlngColumn" : "25.032022,121.474297",
    "learner_birth" : "2008",
    "learner_habit" : "",
    "learner_role" : "自學生",
    "learner_type" : "個人",
    "name" : "MOMO",
    "note" : "6歲,今年準備申請自學",
    "share" : "今年九月可以開始提供",
    "site" : "https://www.facebook.com/profile.php?id=550617967",
    "site2" : "",
    "username" : ""
  }, {
    "address" : "桃園市",
    "ask" : "",
    "child_birth" : "2007",
    "child_birth2" : "2012",
    "connect_me" : "",
    "id" : "1407057911",
    "latlngColumn" : "24.99367,121.30199",
    "learner_habit" : "",
    "learner_role" : "自學家長",
    "learner_type" : "個人",
    "name" : "Angela Peruch",
    "note" : "四個孩子的媽，希望給小孩一個健全快樂的主動學習環境",
    "share" : "http://abcdperuch.blogspot.tw",
    "site" : "https://www.facebook.com/angelaperuch",
    "site2" : "",
    "username" : "angelaperuch"
  }, {
    "address" : "新竹縣湖口",
    "ask" : "..",
    "connect_me" : "email",
    "freetime" : "週六周日",
    "id" : "100000290613126",
    "latlngColumn" : "24.90433,121.04519",
    "learner_birth" : "1984",
    "learner_habit" : "程式",
    "learner_role" : "獨立教育工作者",
    "learner_type" : "個人",
    "name" : "高偉哲",
    "note" : "ＳＯＨＯ族，網站 ＡＰＰ 都有開發",
    "share" : "java, app",
    "site" : "none",
    "site2" : "none",
    "username" : "aliceispig"
  }, {
    "address" : "埤頭",
    "ask" : "如何辦自學",
    "connect_me" : "8924861\n0919391714",
    "freetime" : "下午兩點後\n不定時輪休",
    "id" : "100007974607618",
    "latlngColumn" : "23.89647,120.47679",
    "learner_birth" : "1997",
    "learner_habit" : "看書",
    "learner_role" : "自學生",
    "learner_type" : "個人",
    "name" : "蘇千雅",
    "note" : "乖巧卻帶著小小的叛逆\n很宅\n別人眼中大而化之,其實心思細膩",
    "share" : "無",
    "site" : "https://www.facebook.com/profile.php?id=100007974607618",
    "site2" : "",
    "username" : ""
  }, {
    "address" : "新北市新店區花園新城",
    "ask" : "",
    "connect_me" : "leewayleo717@gmail.com",
    "freetime" : "週日下午",
    "hometown" : "undefined",
    "id" : "100004284313816",
    "invis" : false,
    "latlngColumn" : "24.934944,121.554726",
    "learner_birth" : "1998",
    "learner_habit" : "研究歷史和製作桌遊",
    "learner_role" : "自學生",
    "learner_type" : "三五好友",
    "name" : "曾柏堯",
    "note" : "我是曾柏堯,今年高一,赤赤皮仔自學團的學生,興趣是研究歷史和創作桌遊,預計下學期要提個人自學,希望可以多認識其他高中自學生",
    "share" : "https://www.facebook.com/messages/#!/groups/268798646510231/",
    "site" : "https://www.facebook.com/profile.php?id=100004284313816",
    "site2" : "https://www.facebook.com/messages/#!/groups/268798646510231/",
    "username" : ""
  }, {
    "address" : "桃園市",
    "ask" : "",
    "connect_me" : "",
    "hometown" : "Taipei, Taiwan",
    "id" : "100000961295853",
    "latlngColumn" : "24.99367,121.30199",
    "learner_habit" : "",
    "learner_role" : "自學生家長",
    "name" : "MiMo Lung",
    "note" : "兩個小孩,分別 三歲.1歲半",
    "share" : "中英文童書,自由創作",
    "site" : "https://www.facebook.com/mimo.lung",
    "site2" : "",
    "username" : "mimo.lung"
  }, {
    "address" : "深坑",
    "ask" : "女朋友...（這能算嗎？",
    "connect_me" : "同FB",
    "freetime" : "FB聯絡",
    "id" : "1717161306",
    "latlngColumn" : "24.93848,121.00205",
    "learner_birth" : "1988",
    "learner_habit" : "",
    "learner_role" : "自學生",
    "learner_type" : "個人",
    "name" : "YanAnn Lu",
    "note" : "詳見FB",
    "share" : "哲學",
    "site" : "https://www.facebook.com/LuYanAnn",
    "site2" : "",
    "username" : "LuYanAnn"
  }, {
    "address" : "新北市淡水區",
    "ask" : "日文",
    "connect_me" : "",
    "freetime" : "週日、晚上",
    "id" : "100000254057027",
    "latlngColumn" : "25.16972,121.44078",
    "learner_birth" : "1968",
    "learner_habit" : "電腦",
    "learner_type" : "個人",
    "name" : "Singuan Iap",
    "note" : "我會寫電腦程式，如python, javascript, Objective-C等。如果你會日文/日語，想學電腦程式，我可以帶你學電腦程式，你指導我日文/日語。",
    "share" : "python,iPhone App, UPS, 鋰電池",
    "site" : "https://www.facebook.com/singuan.iap",
    "site2" : "",
    "username" : "singuan.iap"
  }, {
    "address" : "台北市內湖區行善路59巷40弄30號",
    "ask" : "自學團體",
    "connect_me" : "0926-660-080",
    "freetime" : "每天",
    "hometown" : "Taipei, Taiwan",
    "id" : "517104216",
    "latlngColumn" : "25.0572,121.579514",
    "learner_birth" : "1980",
    "learner_habit" : "料理",
    "learner_role" : "自學家長",
    "name" : "洪立蓉",
    "note" : "Be joyful always, pray continually, Give thanks in all circumstances.\n常常喜樂,不住的禱告,凡事謝恩.",
    "share" : "英文",
    "site" : "https://www.facebook.com/need.carol",
    "site2" : "",
    "username" : "need.carol"
  }, {
    "address" : "臺北市信義區虎林街",
    "ask" : "身心靈成長的同伴、同學、法文學習",
    "connect_me" : "<br>\nFacebook: https://www.facebook.com/nitzuching<br>\nLine: nitzuching<br>\nE-mail: chingni1124@gmail.com",
    "freetime" : "週二下午、週三下午",
    "hometown" : "undefined",
    "id" : "100001329787880",
    "invis" : false,
    "latlngColumn" : "25.041929,121.576897",
    "learner_birth" : "1997",
    "learner_habit" : "身心靈成長、體驗各種文化、探索新領域、閱讀、語言、音樂、攝影、繪畫、哲學",
    "learner_role" : "自學生",
    "learner_type" : "三五好友",
    "name" : "Ni Tzu-Ching（倪子晴）",
    "note" : "我十四歲開始自學，目前十六歲。\n\n身心靈成長是目前的生活主軸，落實到生活裡。\n\nhttp://sunshiningmind.blogspot.tw/\n這個部落格是我常用的「工具箱」。\n\nhttp://sunshiningmind.blogspot.tw/p/blog-page.html\n這是部落格的介紹。",
    "share" : "身心靈成長（牌卡解讀、相關討論）、英文",
    "site" : "https://www.facebook.com/nitzuching",
    "site2" : "http://return-to-light.yolasite.com/",
    "username" : "nitzuching"
  }, {
    "address" : "高雄",
    "ask" : "歐語、文化、音樂、藝術展演活動",
    "connect_me" : "",
    "freetime" : "每天下午過後；周末全天",
    "id" : "1828332727",
    "latlngColumn" : "22.62015,120.31226",
    "learner_birth" : "1991",
    "learner_habit" : "語文、音樂",
    "learner_role" : "自學生",
    "learner_type" : "個人",
    "name" : "啊針",
    "note" : "大家好，希望可以在這裡一起努力學習:)",
    "share" : "中文、文化、音樂",
    "site" : "https://www.facebook.com/jia.jane",
    "site2" : "",
    "username" : "jia.jane"
  }, {
    "address" : "台中東區大智路",
    "ask" : "尋求自學管道",
    "child_birth" : "2013",
    "connect_me" : "Jesheng2009@gmail.com",
    "freetime" : "晚間六點後十一點前",
    "hometown" : "Taichung, Taiwan",
    "id" : "100000009235060",
    "invis" : false,
    "latlngColumn" : "24.1372,120.697498",
    "learner_birth" : "1990",
    "learner_habit" : "平面設計。美術設計",
    "learner_role" : "自學家長",
    "learner_type" : "個人",
    "name" : "Zora Jhuang",
    "note" : "一個想為孩子規劃自主學習的媽媽。目前孩子尚未一歲",
    "share" : "photoshop,illustrator",
    "site" : "https://www.facebook.com/zora.jhuang",
    "site2" : "",
    "username" : "zora.jhuang"
  }, {
    "address" : "新北市板橋區",
    "ask" : "想要找一起自學的夥伴",
    "connect_me" : "0988235665. Line: elainelin415",
    "freetime" : "晚上",
    "id" : "100003016938183",
    "latlngColumn" : "25.00952,121.45935",
    "learner_birth" : "1980",
    "learner_habit" : "讀書,畫畫,做手工皂",
    "learner_role" : "自學生家掌",
    "learner_type" : "類學校機構",
    "name" : "Elaine Lin",
    "note" : "一個人照顧兩個孩子的單親媽媽,希望和孩子一起培養獨立思辨的能力",
    "share" : "手工皂教學,網路行銷",
    "site" : "https://www.facebook.com/YSL31",
    "site2" : "",
    "username" : "YSL31"
  }, {
    "address" : "台北市中山區",
    "ask" : "年齡相仿的朋友",
    "child_birth" : 2010,
    "connect_me" : "",
    "follows" : [ 12 ],
    "id" : "799149029",
    "latlngColumn" : "25.068885,121.533056",
    "learner_birth" : "",
    "learner_habit" : "",
    "learner_role" : "自學家長",
    "learner_type" : "個人",
    "name" : "LeiChi Ch",
    "note" : "台北市中山區，想找自學年齡相仿的一起玩與學習",
    "site" : "https://www.facebook.com/leichi.ch",
    "site2" : "",
    "username" : "leichi.ch"
  }, {
    "address" : "捷運善導寺站",
    "ask" : "台語，法文，寫作。",
    "connect_me" : "fb",
    "freetime" : "今年七月後",
    "id" : "100000116619933",
    "latlngColumn" : "25.04475,121.523491",
    "learner_birth" : "1994",
    "learner_habit" : "閱讀，寫作，音樂，音樂劇，泡茶等...",
    "name" : "良屍異友",
    "note" : "我不是自學生，但非常希望能夠讓知識流通。",
    "share" : "西洋文學概論，英文(詳細能幫到如何我不確定",
    "site" : "https://www.facebook.com/belial.chiang",
    "site2" : "",
    "username" : "belial.chiang"
  }, {
    "address" : "台中市清水區",
    "ask" : "自學伙伴或場所",
    "child_birth" : "2011",
    "child_birth2" : "2014",
    "connect_me" : "",
    "freetime" : "周末",
    "id" : "779952709",
    "latlngColumn" : "24.26877,120.55987",
    "learner_birth" : "1982",
    "learner_habit" : "攝影、",
    "learner_role" : "自學家長",
    "learner_type" : "個人",
    "name" : "紅豆斌",
    "note" : "希望小明友能快樂學習",
    "site" : "https://www.facebook.com/red0bean",
    "site2" : "",
    "username" : "red0bean"
  }, {
    "address" : "新竹縣竹北市",
    "ask" : "自學相關資訊",
    "child_birth" : "1996",
    "child_birth2" : "2005",
    "connect_me" : "sophiahsia@gmail.com",
    "freetime" : "5/13整天, 5/14下午, 5/16整天, 周末",
    "hometown" : "Taipei, Taiwan",
    "id" : "100000205498139",
    "latlngColumn" : "24.83955,121.00347",
    "learner_birth" : "1965",
    "learner_habit" : "",
    "learner_role" : "自學家長",
    "learner_type" : "個人",
    "name" : "Sophia Hsia",
    "note" : "希望了解自學及孩子是否適合自學",
    "share" : "人力資源, 法文",
    "site" : "https://www.facebook.com/sophia.hsia.1",
    "site2" : "",
    "username" : "sophia.hsia.1"
  }, {
    "address" : "台北市",
    "ask" : "學生和志同道合的夥伴",
    "connect_me" : "",
    "freetime" : "很彈性",
    "hometown" : "Kaohsiung, Taiwan",
    "id" : "100001463978232",
    "latlngColumn" : "25.0374,121.56355",
    "learner_birth" : "1992年",
    "learner_habit" : "閱讀、心理學、旅行、創作",
    "learner_role" : "獨立教育工作者",
    "learner_type" : "個人",
    "name" : "劉宗宜",
    "note" : "致力於活出生命本身",
    "share" : "教學、心理輔導",
    "site" : "https://www.facebook.com/hjuicine",
    "site2" : "",
    "username" : "hjuicine"
  }, {
    "address" : "高雄市 河堤社區",
    "ask" : "認識在高雄的自學家長夥伴",
    "child_birth" : "2005",
    "child_birth2" : "2011",
    "connect_me" : "0928395440",
    "freetime" : "",
    "id" : "100000534092688",
    "latlngColumn" : "22.9738,120.612504",
    "learner_birth" : "1970",
    "learner_habit" : "手做",
    "learner_role" : "自學家長",
    "learner_type" : "個人",
    "name" : "Janet Tsai",
    "note" : "高中數學教師，預計請一年假陪小孩在家自學",
    "share" : "數學教育",
    "site" : "https://www.facebook.com/janet.tsai.12",
    "site2" : "",
    "username" : "janet.tsai.12"
  }, {
    "address" : "屏東市",
    "ask" : "",
    "connect_me" : "",
    "id" : "100000225194960",
    "latlngColumn" : "22.66209,120.49143",
    "learner_habit" : "經濟學、古典和爵士鋼琴、佛學、英語、德語、街頭健身",
    "learner_role" : "自學生",
    "learner_type" : "個人",
    "name" : "Zark Aurelius",
    "note" : "準備用七個月的時間自學經濟學，希望有深諳相關知識之人可以指點和討論。",
    "site" : "https://www.facebook.com/profile.php?id=100000225194960",
    "site2" : "",
    "username" : ""
  }, {
    "address" : "花蓮市",
    "ask" : "八年級要開始自學",
    "connect_me" : "irene.chen@tccc.org.tw",
    "freetime" : "星期二",
    "id" : "839948227",
    "latlngColumn" : "23.98216,121.60654",
    "learner_birth" : "1956",
    "learner_habit" : "油畫、",
    "learner_role" : "自學家長",
    "learner_type" : "個人",
    "name" : "陳惠琳",
    "note" : "我們生活、動作、存留都在乎祂。For in Him we live and move and have our being.",
    "share" : "油畫、大學生工作資深輔導",
    "site" : "https://www.facebook.com/huilin.chen",
    "site2" : "isotirene@gmail.com",
    "username" : "huilin.chen"
  }, {
    "address" : "台北巿北投區大興街",
    "ask" : "我想申請自學,但不知道怎麼申請",
    "connect_me" : "FB",
    "freetime" : "除睡覺時間",
    "hometown" : "Taipei, Taiwan",
    "id" : "100000195212790",
    "latlngColumn" : "25.13069,121.501564",
    "learner_birth" : "1974",
    "learner_habit" : "",
    "learner_role" : "自學家長",
    "name" : "林憲躍",
    "note" : "大家好",
    "site" : "https://www.facebook.com/tony115722",
    "site2" : "",
    "username" : "tony115722"
  }, {
    "address" : "政治大學",
    "ask" : "",
    "connect_me" : "",
    "hometown" : "Taipei, Taiwan",
    "id" : "100000258241679",
    "invis" : false,
    "latlngColumn" : "24.98757,121.576057",
    "learner_habit" : "",
    "name" : "鄭竣丰",
    "note" : "我愛 陽光\nGive me some sunshine .",
    "site" : "https://www.facebook.com/D.craziest",
    "site2" : "",
    "username" : "D.craziest"
  }, {
    "address" : "台北市金山南路一段9號",
    "ask" : "創業資源",
    "connect_me" : "",
    "freetime" : "週一到週五白天",
    "hometown" : "Taipei, Taiwan",
    "id" : "1711272827",
    "latlngColumn" : "25.041177,121.529291",
    "learner_birth" : "1983",
    "learner_habit" : "學習如何學習",
    "learner_role" : "獨立教育工作者",
    "learner_type" : "個人",
    "name" : "Yi-Ju Wu",
    "note" : "從太陽花學運之後，領悟到自已必須做出改變，擇善固執，做對他人有益之事則是對自已有益之事。雖說創業，其實是為了找出自已如何對他人有所貢獻之處。",
    "share" : "程式開發",
    "site" : "https://www.facebook.com/yijuwu",
    "site2" : "",
    "username" : "yijuwu"
  }, {
    "address" : "台中市東區",
    "ask" : "自學夥伴與族人",
    "connect_me" : "FB",
    "freetime" : "下午吧",
    "hometown" : "Taichung, Taiwan",
    "id" : "100000784713136",
    "latlngColumn" : "24.13738,120.70395",
    "learner_birth" : "1998.7.20",
    "learner_habit" : "花式跳繩、電繪、語言",
    "learner_role" : "自學生",
    "learner_type" : "個人",
    "name" : "天一",
    "note" : "高中準備要申請自學。",
    "share" : "花式跳繩",
    "site" : "https://www.facebook.com/tian.yi.5",
    "site2" : "",
    "username" : "tian.yi.5"
  }, {
    "address" : "新店",
    "ask" : "尋找共玩共學的夥伴",
    "child_birth" : "2010",
    "connect_me" : "anne_chiu1009@yahoo.com.tw",
    "freetime" : "周間上午",
    "hometown" : "Taipei, Taiwan",
    "id" : "1217319067",
    "latlngColumn" : "23.53395,120.29594",
    "learner_birth" : "1976",
    "learner_habit" : "",
    "learner_role" : "自學家長",
    "learner_type" : "團體共學",
    "name" : "Fay Chiu",
    "note" : "希望在大台北地區跟學齡前的小朋友一起共玩共學",
    "site" : "https://www.facebook.com/fay.chiu.71",
    "site2" : "",
    "username" : "fay.chiu.71"
  }, {
    "address" : "新竹市埔頂二路",
    "ask" : "新竹的大孩子自學生夥伴",
    "child_birth" : "2004",
    "connect_me" : "kueiyuchen@gmail.com",
    "freetime" : "週間（平日）",
    "id" : "100002249922038",
    "latlngColumn" : "24.79331,121.009216",
    "learner_birth" : "1973",
    "learner_habit" : "閱讀／DIY／旅遊",
    "learner_role" : "自學家長",
    "learner_type" : "三五好友",
    "name" : "Tan Kuei-yo",
    "note" : "2013年開始自學。\n家中男孩的興趣是圍棋、球類運動（特別是棒球）、桌遊、烹飪。\n孩子的學習風格比較偏向聽覺型及操作型，喜歡以小團體討論的方式進行學習。\n離開體制內的學習道路，是為了讓孩子有時間與空間慢慢探索世界，找到自己感興趣的事，以及將來願意全心投入的志向。\n想找跟我們一樣不被主流升學制度所限，願意放手讓孩子自己選擇道路，並陪伴他、支持他，親子一同學習成長的共學夥伴，一起在自學之路上相互打氣。",
    "share" : "閱讀／DIY心得分享，自學生共學資訊",
    "site" : "https://www.facebook.com/tan.kueiyo",
    "site2" : "",
    "username" : "tan.kueiyo"
  }, {
    "address" : "桃園縣大園鄉",
    "ask" : "素描,漫畫",
    "child_birth" : "2004",
    "child_birth2" : "2004",
    "connect_me" : "",
    "id" : "100000319781229",
    "latlngColumn" : "25.06352,121.19529",
    "learner_birth" : "1976",
    "learner_habit" : "",
    "learner_role" : "自學家長",
    "learner_type" : "三五好友",
    "name" : "李雅倫",
    "note" : "我是住在大園鄉的雅倫,目前帶著雙胞胎自學.",
    "share" : "多材質創作",
    "site" : "https://www.facebook.com/profile.php?id=100000319781229",
    "site2" : "",
    "username" : ""
  }, {
    "address" : "雲林縣古坑鄉中山路242巷97號",
    "ask" : "",
    "child_birth" : "1998",
    "connect_me" : "shindyshen@gmail.com\n0963255264",
    "freetime" : "下班後",
    "id" : "100000024410173",
    "latlngColumn" : "23.64889,120.563553",
    "learner_birth" : "1967",
    "learner_habit" : "",
    "learner_role" : "自學家長",
    "learner_type" : "類學校機構",
    "name" : "沈秀茹",
    "note" : "在雲林古坑三年前引進華德福教育，吸引許多家庭島內移民到古坑，公辦公營的華德福教育漸漸失去華德教育內涵，2014年有近23位學生國中小高中都有，開始團體自學之路。",
    "site" : "https://www.facebook.com/shindy.shen.5",
    "site2" : "",
    "username" : ""
  }, {
    "address" : "台中市西屯區國安一路",
    "ask" : "經驗交流",
    "child_birth" : "2013",
    "connect_me" : "hforhelen.tw@gmail.com",
    "id" : "100000285996550",
    "latlngColumn" : "24.18395,120.626",
    "learner_birth" : "1989",
    "learner_habit" : "(電)吉他，縫紉，歐美電影影集，生物",
    "learner_role" : "自學家長",
    "learner_type" : "個人",
    "name" : "葛奕均",
    "note" : "Ean滿一歲，姑姑正為將來自學做準備。家中有爸爸，媽媽，爺爺，奶奶，姑姑，Ean，小白(狗)，球球(狗)，與西西(龜)。",
    "share" : "",
    "site" : "https://www.facebook.com/send.to.p.mei",
    "site2" : "",
    "username" : ""
  }, {
    "address" : "宜蘭縣冬山鄉冬山路",
    "ask" : "經驗分享",
    "child_birth" : "2002",
    "child_birth2" : "2004",
    "connect_me" : "julius@tingyoung.com",
    "hometown" : "undefined",
    "id" : "100000268294818",
    "invis" : false,
    "latlngColumn" : "24.63479,121.790062",
    "learner_birth" : "1968",
    "learner_habit" : "",
    "learner_role" : "自學家長",
    "learner_type" : "個人",
    "name" : "Julius Chen",
    "nick" : "J",
    "note" : "三年前，由高雄搬到宜蘭\n兩個孩子進到人文國中小就讀\n今年，老大兒子對高爾夫球發生強烈興趣\n所以決定自學",
    "share" : "經驗分享",
    "site" : "https://www.facebook.com/julius.mfchen",
    "site2" : "",
    "username" : ""
  }, {
    "address" : "彰化縣伸港鄉七嘉村七嘉村",
    "ask" : "",
    "connect_me" : "",
    "freetime" : "周末",
    "id" : "1368302490",
    "latlngColumn" : "24.153139,120.495071",
    "learner_habit" : "",
    "learner_role" : "",
    "learner_type" : "",
    "name" : "王晨安",
    "note" : false,
    "site" : "https://www.facebook.com/WangChenAn",
    "site2" : "",
    "username" : ""
  }, {
    "address" : "新北市五股區",
    "ask" : "",
    "child_birth" : "2008",
    "connect_me" : "FB",
    "freetime" : "平日",
    "id" : "100001044090966",
    "latlngColumn" : "25.08293,121.43806",
    "learner_habit" : "動手玩",
    "learner_role" : "自學家長",
    "learner_type" : "",
    "name" : "Sophia Chan",
    "note" : false,
    "site" : "https://www.facebook.com/sophia.chan.374",
    "site2" : "",
    "username" : ""
  }, {
    "address" : "宜蘭縣宜蘭市民族路",
    "ask" : "",
    "child_birth" : "99",
    "child_birth2" : "100",
    "connect_me" : "imjohnniez@gmail.com",
    "id" : "100000146877391",
    "latlngColumn" : "24.75086,121.7454",
    "learner_birth" : "80",
    "learner_habit" : "",
    "learner_role" : "自學家長",
    "learner_type" : "個人",
    "name" : "Johnnie Z Yeh",
    "note" : "大家好",
    "site" : "https://www.facebook.com/ImJohnniez",
    "site2" : "",
    "username" : ""
  }, {
    "address" : "台北市文山區木新路三段",
    "ask" : "",
    "child_birth" : "2013",
    "connect_me" : "hakap@msn.com",
    "freetime" : "六.日",
    "id" : "1485996289",
    "latlngColumn" : "24.98175,121.560989",
    "learner_birth" : "1984",
    "learner_habit" : "",
    "learner_role" : "自學家長",
    "learner_type" : "團體共學",
    "name" : "Maggie Kuo",
    "note" : false,
    "site" : "https://www.facebook.com/maggie.kuo.965",
    "site2" : "",
    "username" : ""
  }, {
    "address" : "桃園縣中壢市健行路1號2樓",
    "ask" : "教語文的老師",
    "child_birth" : "1995",
    "child_birth2" : "2014",
    "connect_me" : "電子郵件：\nchienfulin@ntu.edu.tw\nchienfulin@mettle.idv.tw",
    "freetime" : "週一至週五早上、下午",
    "id" : "100007173104026",
    "latlngColumn" : "24.95277,121.22615",
    "learner_birth" : "1971",
    "learner_habit" : "讀書",
    "learner_role" : "自學家長 + 獨立教育工作者",
    "learner_type" : "三五好友",
    "name" : "林建孚",
    "note" : "我從讀大學即開始家教，現是補習班數學、物理老師。自從第二個女兒出生，我希望能在家教學。",
    "share" : "教數學、物理",
    "site" : "www.facebook.com/chienfu0",
    "site2" : "",
    "username" : ""
  }, {
    "address" : "台北",
    "ask" : "",
    "connect_me" : "",
    "id" : "100001902944161",
    "latlngColumn" : "25.0374,121.56355",
    "learner_habit" : "",
    "learner_role" : "自學生",
    "learner_type" : "類學校機構",
    "name" : "Fu Chien Nina Hsieh",
    "note" : false,
    "site" : "https://www.facebook.com/profile.php?id=100001902944161",
    "site2" : "",
    "username" : ""
  }, {
    "address" : "新北市烏來區",
    "ask" : "一起重新定義「經濟」和「教育」",
    "child_birth" : "2012",
    "child_birth2" : "2014",
    "freetime" : "目前暫無",
    "hometown" : "",
    "id" : "100000207390400",
    "lastUpdate" : 1416095023303,
    "latlngColumn" : "24.87254,121.54752",
    "learner_birth" : "1985",
    "learner_habit" : "玩、設計、安在、健康",
    "learner_role" : "自學生 + 自學家長 + 獨立教育工作者",
    "learner_type" : "三五好友",
    "name" : "唐宗浩",
    "note" : "一切都很簡單，只要無畏無懼",
    "share" : "數學、語文、程式",
    "site" : "http://bestiant.pixnet.net/blog",
    "site2" : "map.alearn.org.tw",
    "username" : false
  } ]
}

}





